### ISSUE TITLE
PDF generation should not be disabled for restricted problems.

### ISSUE THREAD

**Issue by ehhthing** [mcpt/wlmoj#11]
Other than the fact that there are a hundred other ways to save the problem, it is extra bloat that should not exist (it'll cause more merge conflicts too.)

This is a disciplinary issue that has no technical solution, and as such we should not be trying to "fix" it in this way.

**Comment by 6167656e74323431** [comment]
![image](https://user-images.githubusercontent.com/29984862/67173359-7aa33c80-f38c-11e9-83e6-620fe918efc9.png)

**Comment by BenZeng04** [comment]
yes

**Comment by ehhthing** [comment]
Reopened due to awaiting administrative opinion.
