### ISSUE TITLE
v2 API Not Documented

### ISSUE THREAD

**Issue by 0foxes** [mcpt/wlmoj#47]
The v2 API from DMOJ exists in the [source code](https://github.com/mcpt/wlmoj/blob/master/dmoj/urls.py) and is [accessible](https://mcpt.ca/api/v2/submissions?user=BattleMage_), but not documented anywhere on the [website](https://mcpt.ca/api/help/).

**Comment by fluix-dev** [comment]
Thanks, the API is almost identical to the [DMOJ API](https://dmoj.ca/api/). I'll be sure to document the changes after I complete the long awaited [merge](https://github.com/mcpt/wlmoj/pull/43).

**Comment by fluix-dev** [comment]
Alright, the merge is done -- the API is identical to DMOJ API.
